---
- name: Instalando Docker
  shell: |
    if [ $(docker --version > /dev/null 2>&1 ; echo $?) -ne 0 ];then
          curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh
    else
        echo "Docker instalado corretamente"
    fi

- name: Adicionando usuario ubuntu ao grupo Docker
  shell: usermod -aG docker ubuntu > /dev/null 2>&1
