all:
  hosts:
    remote_host:
      ansible_host: app.infsite.org
      ansible_user: root
      ansible_port: 9022
      ansible_ssh_private_key_file: ~/.ssh/id_rsa

  vars:
    ansible_python_interpreter: /usr/bin/python3
