name: '[DISABLED] Initial Configurations'

on:  
  push:
    branches:
      - 'main'

jobs:
  create-secret-store:
    if: |
      github.event.repository.name != 'node-ecs-template' &&
      github.event.head_commit.message == 'Initial commit'
    runs-on: ubuntu-latest 
    steps:
      - name: Trigger Secret Store Workspace Creation
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'LatamNutrien',
              repo: 'node-ecs-app-pattern-v1',
              workflow_id: 'app-instance-configure-secret-store.yml',
              ref: 'app-instance-configure-secret-store/1.0',
              inputs: {
                'identifier': '${{ github.event.repository.name }}'
              }
            }).catch(error => error).then(response => {
              core.debug(response);
              if (response.status !== 204) {
                core.setFailed(`Create workflow_dispatch received status code ${response.status}`);
              }
            });

  configure-repository:
    if: |
      github.event.repository.name != 'node-ecs-template' &&
      github.event.head_commit.message == 'Initial commit'
    needs: create-secret-store
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Repository Configuration
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'LatamNutrien',
              repo: 'node-ecs-app-pattern-v1',
              workflow_id: 'app-instance-configure-repo.yml',
              ref: 'app-instance-configure-repo/1.0',
              inputs: {
                'identifier': '${{ github.event.repository.name }}'
              }
            }).catch(error => error).then(response => {
              core.debug(response);
              if (response.status !== 204) {
                core.setFailed(`Create workflow_dispatch received status code ${response.status}`);
              }
            });


