name: Docker Image CI

on:
  push:
    branches: 
      - "develop"
  pull_request:
    branches:
      - "main"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: secrets......
      env:
        TOKEN: ${{ secrets.USERNAME_REGISTRY }}
        DOCKER_REPO: "marceloviana/websocket"
      run: |
        echo "Downloaded credentials: $TOKEN"
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $DOCKER_REPO:latest
    
    - name: Login in Hub-docker
      run: docker login -u ${{ secrets.USERNAME_REGISTRY }} -p ${{ secrets.PASSWORD_REGISTRY }} docker.io
    - name: Push docker image
      run: docker push $DOCKER_REPO:latest
    - name: Resume vars
      run: echo 'docker login -u ${{ secrets.USERNAME_REGISTRY }} -p ${{ secrets.PASSWORD_REGISTRY }} docker.io'
